# Generated by Django 5.0.1 on 2024-02-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_status_user_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('admin', 'admin'), ('prezident', 'prezident'), ('secret', 'secret'), ('antidoping', 'antidoping'), ('free', 'free')], null=True, verbose_name='Статус'),
        ),
    ]
