# Generated by Django 5.0.1 on 2024-02-27 14:24

import django.db.models.deletion
import django_resized.forms
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, verbose_name='Статус')),
                ('dopusk', models.CharField(max_length=100, verbose_name='Допуск')),
                ('name', models.TextField(verbose_name='Название соревнований')),
                ('disciplina', models.CharField(choices=[('ТЭ', 'ТЭ'), ('ТК', 'ТК'), ('ЖЭ', 'ЖЭ'), ('ЖК', 'ЖК'), ('Все дисциплины', 'Все дисциплины')], verbose_name='Дисциплина')),
                ('vozrast', models.CharField(max_length=100, verbose_name='Возрастная группа')),
                ('start', models.DateField(blank=True, null=True, verbose_name='Начало соревнований')),
                ('finish', models.DateField(blank=True, null=True, verbose_name='Конец соревнований')),
                ('place', models.CharField(max_length=100, verbose_name='Место соревнований')),
                ('srok', models.DateField(blank=True, null=True, verbose_name='Срок приема заявок')),
                ('srokEdit', models.DateField(blank=True, null=True, verbose_name='Срок редактирования заявок')),
            ],
            options={
                'verbose_name': 'Календарь',
                'verbose_name_plural': 'Календарь',
                'db_table': 'calendar',
            },
        ),
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docpath', models.FileField(upload_to='doc/doc/')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'db_table': 'doc',
            },
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('content', models.TextField(max_length=2000, verbose_name='Текст')),
                ('img_Head', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=75, scale=None, size=[1024, 768], upload_to=main.models.user_directory_path)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('count_view', models.IntegerField(blank=True, null=True)),
                ('img_Body', models.ImageField(blank=True, null=True, upload_to=main.models.user_directory_path)),
                ('video', models.URLField(blank=True, null=True)),
                ('like', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'db_table': 'new',
            },
        ),
        migrations.CreateModel(
            name='Table_Norm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Нормативы')),
                ('gender', models.CharField(choices=[('мужской', 'мужской'), ('женский', 'женский')], max_length=100, verbose_name='Пол')),
                ('equipment', models.CharField(choices=[('классика', 'классика'), ('экипировка', 'экипировка')], max_length=100, verbose_name='Экипировка')),
                ('Competition', models.CharField(choices=[('троеборье', 'троеборье'), ('жим', 'жим')], max_length=100, verbose_name='Упражнение')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Таблица с нормативом',
                'verbose_name_plural': 'Таблица с нормативом',
                'db_table': 'norm',
            },
        ),
        migrations.CreateModel(
            name='Table_Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('53', '53'), ('59', '59'), ('66', '66'), ('74', '74'), ('83', '83'), ('93', '93'), ('105', '105'), ('120', '120'), ('120+', '120+'), ('43', '43'), ('47', '47'), ('52', '52'), ('57', '57'), ('63', '63'), ('69', '69'), ('76', '76'), ('84', '84'), ('84+', '84+')], max_length=100, verbose_name='Категории')),
                ('third_j', models.CharField(null=True, verbose_name='Третий юн.')),
                ('second_j', models.CharField(null=True, verbose_name='Второй юн.')),
                ('first_j', models.CharField(null=True, verbose_name='Первый юн.')),
                ('third', models.CharField(null=True, verbose_name='Третий')),
                ('second', models.CharField(null=True, verbose_name='Второй')),
                ('first', models.CharField(null=True, verbose_name='Первый')),
                ('kms', models.CharField(null=True, verbose_name='КМС')),
                ('ms', models.CharField(null=True, verbose_name='МС')),
                ('msmk', models.CharField(null=True, verbose_name='МСМК')),
                ('cut', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.table_norm')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категория',
                'db_table': 'cut',
            },
        ),
    ]
