# Generated by Django 5.0.1 on 2024-01-25 14:50

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('content', models.TextField(max_length=2000, verbose_name='Текст')),
                ('img_Head', models.ImageField(upload_to=main.models.user_directory_path)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('count_view', models.IntegerField(blank=True, null=True)),
                ('img_Body', models.ImageField(blank=True, null=True, upload_to=main.models.user_directory_path)),
                ('video', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'db_table': 'new',
            },
        ),
    ]
