# Generated by Django 5.0.1 on 2024-02-07 06:31

import django_resized.forms
import main.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='img_Head',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=75, scale=None, size=[1024, 768], upload_to=main.models.user_directory_path),
        ),
    ]
