# Generated by Django 5.0.1 on 2024-02-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='zayav',
            field=models.DateField(blank=True, null=True, verbose_name='Ссылка на заявку, если нужно'),
        ),
    ]
