# Generated by Django 5.0.1 on 2024-02-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_calendar_zayav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='zayav',
            field=models.CharField(blank=True, null=True, verbose_name='Ссылка на заявку, если нужно'),
        ),
    ]
