# Generated by Django 5.0.1 on 2024-02-28 07:53

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_calendar_zayav'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='img_Body',
        ),
        migrations.AddField(
            model_name='new',
            name='img_Body_1',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.user_directory_path, verbose_name='Фото1 ленты'),
        ),
        migrations.AddField(
            model_name='new',
            name='img_Body_2',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.user_directory_path, verbose_name='Фото2 ленты'),
        ),
        migrations.AddField(
            model_name='new',
            name='img_Body_3',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.user_directory_path, verbose_name='Фото3 ленты'),
        ),
        migrations.AddField(
            model_name='new',
            name='img_Body_4',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.user_directory_path, verbose_name='Фото4 ленты'),
        ),
        migrations.AddField(
            model_name='new',
            name='img_Body_5',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.user_directory_path, verbose_name='Фото5 ленты'),
        ),
        migrations.AddField(
            model_name='new',
            name='img_Body_6',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.user_directory_path, verbose_name='Фото6 ленты'),
        ),
    ]
