# Generated by Django 5.0.1 on 2024-03-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_table_record_alter_table_cat_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_cat',
            name='category',
            field=models.CharField(choices=[('53', '53'), ('59', '59'), ('66', '66'), ('74', '74'), ('83', '83'), ('93', '93'), ('105', '105'), ('120', '120'), ('120+', '120+'), ('43', '43-жен'), ('47', '47-жен'), ('52', '52-жен'), ('57', '57-жен'), ('63', '63-жен'), ('69', '69-жен'), ('72', '72-жен'), ('76', '76-жен'), ('84', '84-жен'), ('84+', '84+-жен')], max_length=100, verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='table_cat_record',
            name='category',
            field=models.CharField(choices=[('53', '53'), ('59', '59'), ('66', '66'), ('74', '74'), ('83', '83'), ('93', '93'), ('105', '105'), ('120', '120'), ('120+', '120+'), ('43', '43-жен'), ('47', '47-жен'), ('52', '52-жен'), ('57', '57-жен'), ('63', '63-жен'), ('69', '69-жен'), ('72', '72-жен'), ('76', '76-жен'), ('84', '84-жен'), ('84+', '84+-жен')], max_length=100, verbose_name='Категории'),
        ),
    ]
