# Generated by Django 5.0.1 on 2024-03-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_table_cat_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='count_view',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='like',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
