# Generated by Django 5.0.1 on 2024-03-03 16:33

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_new_count_view_alter_new_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True, verbose_name='Заголовок альбома')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Описание альбома')),
                ('image', models.ImageField(blank=True, null=True, upload_to=main.models.foto_directory_path, verbose_name='Аватар альбома')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата опубликования альбома')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
                'db_table': 'Albom',
            },
        ),
    ]
