# Generated by Django 5.0.1 on 2024-03-08 18:51

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docpath', models.FileField(upload_to='doc/polog/')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Положение',
                'verbose_name_plural': 'Положение',
                'db_table': 'polog',
            },
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docpath', models.FileField(upload_to='doc/protocol/')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Протокол',
                'verbose_name_plural': 'Протокол',
                'db_table': 'protocol',
            },
        ),
        migrations.AlterField(
            model_name='new',
            name='content',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='new',
            name='count_view',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Счетчик просмотров'),
        ),
        migrations.AlterField(
            model_name='new',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата новости'),
        ),
        migrations.AlterField(
            model_name='new',
            name='img_Head',
            field=models.ImageField(upload_to=main.models.user_directory_path, verbose_name='Аватарка ленты'),
        ),
        migrations.AlterField(
            model_name='new',
            name='like',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Лайки(не собаки)'),
        ),
        migrations.AlterField(
            model_name='new',
            name='video',
            field=models.URLField(blank=True, null=True, verbose_name='ссылка с ютуб'),
        ),
    ]
